baseURL = "https://siqitan.com"
languageCode = "en-uk"
title = "Musings"
theme = "yinyang"
DefaultContentLanguage = "en"

[params.author]
  name = "Andrew Tan"
  homepage = "https://siqitan.com/"

[params]
headTitle = "Andrew Tan"
extraHead = ''
mainSections = ["posts"]
layout = "home"

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://siqitan.com"

[[params.socials]]
name = "Twitter"
link = "https://x.com/andrewsqtan"